Repository wecode-bootcamp-korea/33-1st-crowsSeven-backend, pull requests merged in 2022-05, with the labels that each got.

#1 initial-setting
  crow/.gitignore
  crow/crow/__init__.py
  crow/crow/asgi.py
  crow/crow/settings.py
  crow/crow/urls.py
  crow/crow/wsgi.py
  crow/manage.py
  crow/requirements.txt
Labels: 완료

#3 새로운 모델링
  crow/carts/migrations/0001_initial.py
  crow/orders/migrations/0001_initial.py
  crow/products/migrations/0001_initial.py
  crow/products/models.py
  crow/review/views.py
  crow/reviews/migrations/0001_initial.py
  crow/reviews/models.py
  crow/users/migrations/0001_initial.py
  crow/users/migrations/0002_remove_user_optional_agreement_optionalagreement.py
  crow/users/migrations/0003_user_optional_agreement_delete_optionalagreement.py
  crow/users/models.py
Labels: 완료

#8 회원가입API 구현
  crow/urls.py
  users/urls.py
  users/views.py
Labels: 완료

#9 회원가입api수정본1
  users/views.py
Labels: 멘토 리뷰 요청

#10 LoginAPI 구현
  crow/settings.py
  users/urls.py
  users/views.py
Labels: 완료

#12 제품 상세페이지 API 구현
  crow/urls.py
  products/urls.py
  products/views.py
Labels: 완료

#13 모델링 삭제 및 새로운 모델링 작성
  carts/migrations/0001_initial.py
  orders/migrations/0001_initial.py
  orders/migrations/0002_order_paymentmethod.py
  orders/models.py
  products/migrations/0001_initial.py
  products/migrations/0002_rename_optiona_existence_product_optional_existence.py
  products/models.py
  reviews/migrations/0001_initial.py
  reviews/models.py
  users/migrations/0001_initial.py
Labels: 완료

#11 decorator파일 생성
  utils.py
Labels: 완료

#17 [33기 김민정]리뷰페이지 상세보기 기능
  reviews/urls.py
  reviews/views.py
Labels: Conflict 해결 요청, 완료
